### PR TITLE
Prevent dropdown from re-appearing after closing

### PR DESCRIPTION
**Pull request by cdata**

### CODE REVIEW

**Comment by cdata** [comment]
TL;DR the compiler fixed something that shouldn't have been there in the first place, which caused a bug. Removing the formerly broken thing fixes the bug.

/cc @notwaldorf

**Comment by cdata** [comment]
(This addresses #9)

**Comment by cdata** [comment]
(also addresses polymerelements/paper-menu-button#4)

**Comment by morethanreal** [comment]
lgtm

**Pull request merged**
