### PR TITLE
Prevent duplicate scroll locks, fixes #47

### LINKED ISSUE #47: ScollLock stack adds up when opening multiple times
- When a dropdown is already open and the open is called again `_renderClosed` doesn't get called and thus ScollLock stack contains two items
- Now closing the dropdown removes only one item from the stack
- Result: dropdown is closed but ScrollLock is still active

Solution: call `removeScollLock` in `_renderOpened` before `pushScrollLock`. Sending a PR.

### PR DESCRIPTION
**Pull request by rubenstolk**
fixes #47

### CODE REVIEW

**Comment by cdata** [comment]
Thanks for reporting this, and for the PR. I think that the design is reasonable, but could you please include a regression test?

**Comment by rubenstolk** [comment]
Hey @cdata did that, please have a look. Also I'm now preventing a duplicate entry in the locking stack in the `pushScrollLock` itself instead of in the `_renderOpened` logic, I think that makes more sense!

**Comment by rubenstolk** [comment]
Not sure why all the tests started failing on travis, they definitely all pass locally and I definitely didn't change that much...

**Comment by cdata** [comment]
It looks like these tests have failures due to a subtle change in a transitive dependency. I filed an issue for this at https://github.com/PolymerElements/iron-dropdown/issues/57. Otherwise this change LGTM!

**Pull request merged**
