### PR TITLE
animation configs are Arrays

### LINKED ISSUE #116: Dropdown tries to concat animation configs objects
https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html#L312

The animation configs on this line are objects and they cannot use concat

### PR DESCRIPTION
**Pull request by valdrinkoshi**
Fixes #116

### CODE REVIEW

**Comment by valdrinkoshi** [comment]
@helenxu @cdata could you PTAL & see if this solves the issue?

**Comment by cdata** [comment]
LGTM 👍

**Comment by valdrinkoshi** [comment]
So apparently https://github.com/PolymerElements/iron-dropdown/pull/84/ introduced a regression, since `animationConfig.open/close` can be either objects or arrays https://github.com/PolymerElements/neon-animation
Will fix it in this PR

**Comment by cdata** [comment]
👯‍♂️

**Pull request merged**
